name: Update Pinecone Index

on:
  push:
    paths:
      - 'portfolio/public/data.json'  
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Pinecone Update API
        run: |
          curl -X POST https://dsic5qduwc.execute-api.us-east-1.amazonaws.com/test/portfolio-updater
